@api_HostAddress = http://localhost:5036

GET {{api_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{api_HostAddress}}/messages/

###
POST {{api_HostAddress}}/messages/
Content-Type: application/json

{
    "id": 1,
    "msg": "hello mama",
    "sender": 1,
    "target": 2
}

###
DELETE {{api_HostAddress}}/messages/1